"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "infinite-minds"
compatibility_date = "2026-02-05"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "out"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
